"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class ecat_debug_power_data_lcmt(object):
    __slots__ = ["emy_stop", "voltage", "current", "temperature", "charge", "health", "cycle"]

    __typenames__ = ["int8_t", "int32_t", "int32_t", "int8_t", "int8_t", "int8_t", "int16_t"]

    __dimensions__ = [None, None, None, None, None, None, None]

    def __init__(self):
        self.emy_stop = 0
        self.voltage = 0
        self.current = 0
        self.temperature = 0
        self.charge = 0
        self.health = 0
        self.cycle = 0

    def encode(self):
        buf = BytesIO()
        buf.write(ecat_debug_power_data_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">biibbbh", self.emy_stop, self.voltage, self.current, self.temperature, self.charge, self.health, self.cycle))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ecat_debug_power_data_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ecat_debug_power_data_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = ecat_debug_power_data_lcmt()
        self.emy_stop, self.voltage, self.current, self.temperature, self.charge, self.health, self.cycle = struct.unpack(">biibbbh", buf.read(14))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if ecat_debug_power_data_lcmt in parents: return 0
        tmphash = (0x3d8718855cebdd9a) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if ecat_debug_power_data_lcmt._packed_fingerprint is None:
            ecat_debug_power_data_lcmt._packed_fingerprint = struct.pack(">Q", ecat_debug_power_data_lcmt._get_hash_recursive([]))
        return ecat_debug_power_data_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", ecat_debug_power_data_lcmt._get_packed_fingerprint())[0]

