"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class error_data_lcmt(object):
    __slots__ = ["timestamp", "seq_num", "error_flag", "motion_control_fsm", "motion_control_error_stack", "hard_error_leg_left", "hard_error_leg_right", "hard_error_arm_left", "hard_error_arm_right", "hard_error_waist", "hard_error_head", "hard_error_hand", "hard_error_gripper", "hard_error_leg_ft", "hard_error_arm_ft", "hard_error_ecat_stack", "hard_error_imu", "hard_error_power", "hard_error_other_stack", "ecat_node_num"]

    __typenames__ = ["int64_t", "int64_t", "byte", "byte", "int32_t", "byte", "byte", "byte", "byte", "byte", "byte", "byte", "byte", "byte", "byte", "byte", "byte", "byte", "int32_t", "byte"]

    __dimensions__ = [None, None, None, None, [3], [6], [6], [7], [7], [2], [2], [2], [2], [2], [2], [4], None, None, [3], [3]]

    def __init__(self):
        self.timestamp = 0
        self.seq_num = 0
        self.error_flag = 0
        self.motion_control_fsm = 0
        self.motion_control_error_stack = [ 0 for dim0 in range(3) ]
        self.hard_error_leg_left = b""
        self.hard_error_leg_right = b""
        self.hard_error_arm_left = b""
        self.hard_error_arm_right = b""
        self.hard_error_waist = b""
        self.hard_error_head = b""
        self.hard_error_hand = b""
        self.hard_error_gripper = b""
        self.hard_error_leg_ft = b""
        self.hard_error_arm_ft = b""
        self.hard_error_ecat_stack = b""
        self.hard_error_imu = 0
        self.hard_error_power = 0
        self.hard_error_other_stack = [ 0 for dim0 in range(3) ]
        self.ecat_node_num = b""

    def encode(self):
        buf = BytesIO()
        buf.write(error_data_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qqBB", self.timestamp, self.seq_num, self.error_flag, self.motion_control_fsm))
        buf.write(struct.pack('>3i', *self.motion_control_error_stack[:3]))
        buf.write(bytearray(self.hard_error_leg_left[:6]))
        buf.write(bytearray(self.hard_error_leg_right[:6]))
        buf.write(bytearray(self.hard_error_arm_left[:7]))
        buf.write(bytearray(self.hard_error_arm_right[:7]))
        buf.write(bytearray(self.hard_error_waist[:2]))
        buf.write(bytearray(self.hard_error_head[:2]))
        buf.write(bytearray(self.hard_error_hand[:2]))
        buf.write(bytearray(self.hard_error_gripper[:2]))
        buf.write(bytearray(self.hard_error_leg_ft[:2]))
        buf.write(bytearray(self.hard_error_arm_ft[:2]))
        buf.write(bytearray(self.hard_error_ecat_stack[:4]))
        buf.write(struct.pack(">BB", self.hard_error_imu, self.hard_error_power))
        buf.write(struct.pack('>3i', *self.hard_error_other_stack[:3]))
        buf.write(bytearray(self.ecat_node_num[:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != error_data_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return error_data_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = error_data_lcmt()
        self.timestamp, self.seq_num, self.error_flag, self.motion_control_fsm = struct.unpack(">qqBB", buf.read(18))
        self.motion_control_error_stack = struct.unpack('>3i', buf.read(12))
        self.hard_error_leg_left = buf.read(6)
        self.hard_error_leg_right = buf.read(6)
        self.hard_error_arm_left = buf.read(7)
        self.hard_error_arm_right = buf.read(7)
        self.hard_error_waist = buf.read(2)
        self.hard_error_head = buf.read(2)
        self.hard_error_hand = buf.read(2)
        self.hard_error_gripper = buf.read(2)
        self.hard_error_leg_ft = buf.read(2)
        self.hard_error_arm_ft = buf.read(2)
        self.hard_error_ecat_stack = buf.read(4)
        self.hard_error_imu, self.hard_error_power = struct.unpack(">BB", buf.read(2))
        self.hard_error_other_stack = struct.unpack('>3i', buf.read(12))
        self.ecat_node_num = buf.read(3)
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if error_data_lcmt in parents: return 0
        tmphash = (0xfe7720063d6da75c) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if error_data_lcmt._packed_fingerprint is None:
            error_data_lcmt._packed_fingerprint = struct.pack(">Q", error_data_lcmt._get_hash_recursive([]))
        return error_data_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", error_data_lcmt._get_packed_fingerprint())[0]

