"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class floating_base_cmd_lcmt(object):
    __slots__ = ["delta_pos_cmd", "abs_ori_cmd"]

    __typenames__ = ["float", "float"]

    __dimensions__ = [[3], [3]]

    def __init__(self):
        self.delta_pos_cmd = [ 0.0 for dim0 in range(3) ]
        self.abs_ori_cmd = [ 0.0 for dim0 in range(3) ]

    def encode(self):
        buf = BytesIO()
        buf.write(floating_base_cmd_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>3f', *self.delta_pos_cmd[:3]))
        buf.write(struct.pack('>3f', *self.abs_ori_cmd[:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != floating_base_cmd_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return floating_base_cmd_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = floating_base_cmd_lcmt()
        self.delta_pos_cmd = struct.unpack('>3f', buf.read(12))
        self.abs_ori_cmd = struct.unpack('>3f', buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if floating_base_cmd_lcmt in parents: return 0
        tmphash = (0x92bcaeab760a9b3) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if floating_base_cmd_lcmt._packed_fingerprint is None:
            floating_base_cmd_lcmt._packed_fingerprint = struct.pack(">Q", floating_base_cmd_lcmt._get_hash_recursive([]))
        return floating_base_cmd_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", floating_base_cmd_lcmt._get_packed_fingerprint())[0]

