"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class grid_map_lcmt(object):
    __slots__ = ["height_elevation"]

    __typenames__ = ["float"]

    __dimensions__ = [[315]]

    def __init__(self):
        self.height_elevation = [ 0.0 for dim0 in range(315) ]

    def encode(self):
        buf = BytesIO()
        buf.write(grid_map_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>315f', *self.height_elevation[:315]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != grid_map_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return grid_map_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = grid_map_lcmt()
        self.height_elevation = struct.unpack('>315f', buf.read(1260))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if grid_map_lcmt in parents: return 0
        tmphash = (0xfd3de10beda5322e) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if grid_map_lcmt._packed_fingerprint is None:
            grid_map_lcmt._packed_fingerprint = struct.pack(">Q", grid_map_lcmt._get_hash_recursive([]))
        return grid_map_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", grid_map_lcmt._get_packed_fingerprint())[0]

