"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class howbc_accuracy_lcmt(object):
    __slots__ = ["eom_step", "eeNoMotion_step", "eeWrenchIneq_step", "com_step", "body_step", "swingLeg_step", "hand_step", "eeWrenchReg_step", "ddqRef_step", "eom_all", "eeNoMotion_all", "eeWrenchIneq_all", "com_all", "body_all", "swingLeg_all", "hand_all", "eeWrenchReg_all", "ddqRef_all", "tau_ff_raw", "tau_ff_limit", "tau_base", "ddq_wrench0", "ddq_wrench1", "ddq_wrench2"]

    __typenames__ = ["float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float"]

    __dimensions__ = [[6], [12], [24], [6], [6], [12], [12], [12], [36], [6], [12], [24], [6], [6], [12], [12], [12], [36], [30], [30], [6], [48], [48], [48]]

    def __init__(self):
        self.eom_step = [ 0.0 for dim0 in range(6) ]
        self.eeNoMotion_step = [ 0.0 for dim0 in range(12) ]
        self.eeWrenchIneq_step = [ 0.0 for dim0 in range(24) ]
        self.com_step = [ 0.0 for dim0 in range(6) ]
        self.body_step = [ 0.0 for dim0 in range(6) ]
        self.swingLeg_step = [ 0.0 for dim0 in range(12) ]
        self.hand_step = [ 0.0 for dim0 in range(12) ]
        self.eeWrenchReg_step = [ 0.0 for dim0 in range(12) ]
        self.ddqRef_step = [ 0.0 for dim0 in range(36) ]
        self.eom_all = [ 0.0 for dim0 in range(6) ]
        self.eeNoMotion_all = [ 0.0 for dim0 in range(12) ]
        self.eeWrenchIneq_all = [ 0.0 for dim0 in range(24) ]
        self.com_all = [ 0.0 for dim0 in range(6) ]
        self.body_all = [ 0.0 for dim0 in range(6) ]
        self.swingLeg_all = [ 0.0 for dim0 in range(12) ]
        self.hand_all = [ 0.0 for dim0 in range(12) ]
        self.eeWrenchReg_all = [ 0.0 for dim0 in range(12) ]
        self.ddqRef_all = [ 0.0 for dim0 in range(36) ]
        self.tau_ff_raw = [ 0.0 for dim0 in range(30) ]
        self.tau_ff_limit = [ 0.0 for dim0 in range(30) ]
        self.tau_base = [ 0.0 for dim0 in range(6) ]
        self.ddq_wrench0 = [ 0.0 for dim0 in range(48) ]
        self.ddq_wrench1 = [ 0.0 for dim0 in range(48) ]
        self.ddq_wrench2 = [ 0.0 for dim0 in range(48) ]

    def encode(self):
        buf = BytesIO()
        buf.write(howbc_accuracy_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>6f', *self.eom_step[:6]))
        buf.write(struct.pack('>12f', *self.eeNoMotion_step[:12]))
        buf.write(struct.pack('>24f', *self.eeWrenchIneq_step[:24]))
        buf.write(struct.pack('>6f', *self.com_step[:6]))
        buf.write(struct.pack('>6f', *self.body_step[:6]))
        buf.write(struct.pack('>12f', *self.swingLeg_step[:12]))
        buf.write(struct.pack('>12f', *self.hand_step[:12]))
        buf.write(struct.pack('>12f', *self.eeWrenchReg_step[:12]))
        buf.write(struct.pack('>36f', *self.ddqRef_step[:36]))
        buf.write(struct.pack('>6f', *self.eom_all[:6]))
        buf.write(struct.pack('>12f', *self.eeNoMotion_all[:12]))
        buf.write(struct.pack('>24f', *self.eeWrenchIneq_all[:24]))
        buf.write(struct.pack('>6f', *self.com_all[:6]))
        buf.write(struct.pack('>6f', *self.body_all[:6]))
        buf.write(struct.pack('>12f', *self.swingLeg_all[:12]))
        buf.write(struct.pack('>12f', *self.hand_all[:12]))
        buf.write(struct.pack('>12f', *self.eeWrenchReg_all[:12]))
        buf.write(struct.pack('>36f', *self.ddqRef_all[:36]))
        buf.write(struct.pack('>30f', *self.tau_ff_raw[:30]))
        buf.write(struct.pack('>30f', *self.tau_ff_limit[:30]))
        buf.write(struct.pack('>6f', *self.tau_base[:6]))
        buf.write(struct.pack('>48f', *self.ddq_wrench0[:48]))
        buf.write(struct.pack('>48f', *self.ddq_wrench1[:48]))
        buf.write(struct.pack('>48f', *self.ddq_wrench2[:48]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != howbc_accuracy_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return howbc_accuracy_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = howbc_accuracy_lcmt()
        self.eom_step = struct.unpack('>6f', buf.read(24))
        self.eeNoMotion_step = struct.unpack('>12f', buf.read(48))
        self.eeWrenchIneq_step = struct.unpack('>24f', buf.read(96))
        self.com_step = struct.unpack('>6f', buf.read(24))
        self.body_step = struct.unpack('>6f', buf.read(24))
        self.swingLeg_step = struct.unpack('>12f', buf.read(48))
        self.hand_step = struct.unpack('>12f', buf.read(48))
        self.eeWrenchReg_step = struct.unpack('>12f', buf.read(48))
        self.ddqRef_step = struct.unpack('>36f', buf.read(144))
        self.eom_all = struct.unpack('>6f', buf.read(24))
        self.eeNoMotion_all = struct.unpack('>12f', buf.read(48))
        self.eeWrenchIneq_all = struct.unpack('>24f', buf.read(96))
        self.com_all = struct.unpack('>6f', buf.read(24))
        self.body_all = struct.unpack('>6f', buf.read(24))
        self.swingLeg_all = struct.unpack('>12f', buf.read(48))
        self.hand_all = struct.unpack('>12f', buf.read(48))
        self.eeWrenchReg_all = struct.unpack('>12f', buf.read(48))
        self.ddqRef_all = struct.unpack('>36f', buf.read(144))
        self.tau_ff_raw = struct.unpack('>30f', buf.read(120))
        self.tau_ff_limit = struct.unpack('>30f', buf.read(120))
        self.tau_base = struct.unpack('>6f', buf.read(24))
        self.ddq_wrench0 = struct.unpack('>48f', buf.read(192))
        self.ddq_wrench1 = struct.unpack('>48f', buf.read(192))
        self.ddq_wrench2 = struct.unpack('>48f', buf.read(192))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if howbc_accuracy_lcmt in parents: return 0
        tmphash = (0x1e8a6b5023454abb) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if howbc_accuracy_lcmt._packed_fingerprint is None:
            howbc_accuracy_lcmt._packed_fingerprint = struct.pack(">Q", howbc_accuracy_lcmt._get_hash_recursive([]))
        return howbc_accuracy_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", howbc_accuracy_lcmt._get_packed_fingerprint())[0]

