"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class howbc_time_lcmt(object):
    __slots__ = ["t_total", "t_obj", "t_task_cons", "t_final_verify", "t_torque", "t_pub", "prior_num", "prior_task", "contact_count"]

    __typenames__ = ["float", "float", "float", "float", "float", "float", "float", "float", "int32_t"]

    __dimensions__ = [None, None, None, None, None, None, None, [10], None]

    def __init__(self):
        self.t_total = 0.0
        self.t_obj = 0.0
        self.t_task_cons = 0.0
        self.t_final_verify = 0.0
        self.t_torque = 0.0
        self.t_pub = 0.0
        self.prior_num = 0.0
        self.prior_task = [ 0.0 for dim0 in range(10) ]
        self.contact_count = 0

    def encode(self):
        buf = BytesIO()
        buf.write(howbc_time_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">fffffff", self.t_total, self.t_obj, self.t_task_cons, self.t_final_verify, self.t_torque, self.t_pub, self.prior_num))
        buf.write(struct.pack('>10f', *self.prior_task[:10]))
        buf.write(struct.pack(">i", self.contact_count))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != howbc_time_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return howbc_time_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = howbc_time_lcmt()
        self.t_total, self.t_obj, self.t_task_cons, self.t_final_verify, self.t_torque, self.t_pub, self.prior_num = struct.unpack(">fffffff", buf.read(28))
        self.prior_task = struct.unpack('>10f', buf.read(40))
        self.contact_count = struct.unpack(">i", buf.read(4))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if howbc_time_lcmt in parents: return 0
        tmphash = (0x66bece2a910ec18f) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if howbc_time_lcmt._packed_fingerprint is None:
            howbc_time_lcmt._packed_fingerprint = struct.pack(">Q", howbc_time_lcmt._get_hash_recursive([]))
        return howbc_time_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", howbc_time_lcmt._get_packed_fingerprint())[0]

