"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class lcm_command_lcmt(object):
    __slots__ = ["robot_fsm", "x_vel_des", "y_vel_des", "yaw_vel_des", "rpy_des", "body_height", "step_height", "leg_des"]

    __typenames__ = ["int8_t", "float", "float", "float", "float", "float", "float", "float"]

    __dimensions__ = [None, None, None, None, [3], None, None, [4, 3]]

    def __init__(self):
        self.robot_fsm = 0
        self.x_vel_des = 0.0
        self.y_vel_des = 0.0
        self.yaw_vel_des = 0.0
        self.rpy_des = [ 0.0 for dim0 in range(3) ]
        self.body_height = 0.0
        self.step_height = 0.0
        self.leg_des = [ [ 0.0 for dim1 in range(3) ] for dim0 in range(4) ]

    def encode(self):
        buf = BytesIO()
        buf.write(lcm_command_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">bfff", self.robot_fsm, self.x_vel_des, self.y_vel_des, self.yaw_vel_des))
        buf.write(struct.pack('>3f', *self.rpy_des[:3]))
        buf.write(struct.pack(">ff", self.body_height, self.step_height))
        for i0 in range(4):
            buf.write(struct.pack('>3f', *self.leg_des[i0][:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcm_command_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcm_command_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = lcm_command_lcmt()
        self.robot_fsm, self.x_vel_des, self.y_vel_des, self.yaw_vel_des = struct.unpack(">bfff", buf.read(13))
        self.rpy_des = struct.unpack('>3f', buf.read(12))
        self.body_height, self.step_height = struct.unpack(">ff", buf.read(8))
        self.leg_des = []
        for i0 in range(4):
            self.leg_des.append(struct.unpack('>3f', buf.read(12)))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if lcm_command_lcmt in parents: return 0
        tmphash = (0xc8e06aaf6ccb6359) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if lcm_command_lcmt._packed_fingerprint is None:
            lcm_command_lcmt._packed_fingerprint = struct.pack(">Q", lcm_command_lcmt._get_hash_recursive([]))
        return lcm_command_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lcm_command_lcmt._get_packed_fingerprint())[0]

