"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class lowlevel_command_struct(object):
    __slots__ = ["x_vel_des", "y_vel_des", "yaw_vel_des", "z_des", "stop", "is_stair"]

    __typenames__ = ["float", "float", "float", "float", "float", "int8_t"]

    __dimensions__ = [None, None, None, None, None, None]

    def __init__(self):
        self.x_vel_des = 0.0
        self.y_vel_des = 0.0
        self.yaw_vel_des = 0.0
        self.z_des = 0.0
        self.stop = 0.0
        self.is_stair = 0

    def encode(self):
        buf = BytesIO()
        buf.write(lowlevel_command_struct._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">fffffb", self.x_vel_des, self.y_vel_des, self.yaw_vel_des, self.z_des, self.stop, self.is_stair))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lowlevel_command_struct._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lowlevel_command_struct._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = lowlevel_command_struct()
        self.x_vel_des, self.y_vel_des, self.yaw_vel_des, self.z_des, self.stop, self.is_stair = struct.unpack(">fffffb", buf.read(21))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if lowlevel_command_struct in parents: return 0
        tmphash = (0x142cab22f0b85b50) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if lowlevel_command_struct._packed_fingerprint is None:
            lowlevel_command_struct._packed_fingerprint = struct.pack(">Q", lowlevel_command_struct._get_hash_recursive([]))
        return lowlevel_command_struct._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lowlevel_command_struct._get_packed_fingerprint())[0]

