"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class manager_ctrl_data_lcmt(object):
    __slots__ = ["ctrl_arr"]

    __typenames__ = ["int8_t"]

    __dimensions__ = [[16]]

    def __init__(self):
        self.ctrl_arr = [ 0 for dim0 in range(16) ]

    def encode(self):
        buf = BytesIO()
        buf.write(manager_ctrl_data_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>16b', *self.ctrl_arr[:16]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != manager_ctrl_data_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return manager_ctrl_data_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = manager_ctrl_data_lcmt()
        self.ctrl_arr = struct.unpack('>16b', buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if manager_ctrl_data_lcmt in parents: return 0
        tmphash = (0x594339f99a5dd80a) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if manager_ctrl_data_lcmt._packed_fingerprint is None:
            manager_ctrl_data_lcmt._packed_fingerprint = struct.pack(">Q", manager_ctrl_data_lcmt._get_hash_recursive([]))
        return manager_ctrl_data_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", manager_ctrl_data_lcmt._get_packed_fingerprint())[0]

