"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class navi_ctrl_command_lcmt(object):
    __slots__ = ["foot_traj", "com_traj", "time_interval", "update_flag", "timestamp", "p"]

    __typenames__ = ["float", "float", "float", "int8_t", "int64_t", "float"]

    __dimensions__ = [[4, 2, 3], [10, 12], None, None, None, [3]]

    def __init__(self):
        self.foot_traj = [ [ [ 0.0 for dim2 in range(3) ] for dim1 in range(2) ] for dim0 in range(4) ]
        self.com_traj = [ [ 0.0 for dim1 in range(12) ] for dim0 in range(10) ]
        self.time_interval = 0.0
        self.update_flag = 0
        self.timestamp = 0
        self.p = [ 0.0 for dim0 in range(3) ]

    def encode(self):
        buf = BytesIO()
        buf.write(navi_ctrl_command_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        for i0 in range(4):
            for i1 in range(2):
                buf.write(struct.pack('>3f', *self.foot_traj[i0][i1][:3]))
        for i0 in range(10):
            buf.write(struct.pack('>12f', *self.com_traj[i0][:12]))
        buf.write(struct.pack(">fbq", self.time_interval, self.update_flag, self.timestamp))
        buf.write(struct.pack('>3f', *self.p[:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != navi_ctrl_command_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return navi_ctrl_command_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = navi_ctrl_command_lcmt()
        self.foot_traj = []
        for i0 in range(4):
            self.foot_traj.append([])
            for i1 in range(2):
                self.foot_traj[i0].append(struct.unpack('>3f', buf.read(12)))
        self.com_traj = []
        for i0 in range(10):
            self.com_traj.append(struct.unpack('>12f', buf.read(48)))
        self.time_interval, self.update_flag, self.timestamp = struct.unpack(">fbq", buf.read(13))
        self.p = struct.unpack('>3f', buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if navi_ctrl_command_lcmt in parents: return 0
        tmphash = (0xe1227428839460b5) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if navi_ctrl_command_lcmt._packed_fingerprint is None:
            navi_ctrl_command_lcmt._packed_fingerprint = struct.pack(">Q", navi_ctrl_command_lcmt._get_hash_recursive([]))
        return navi_ctrl_command_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", navi_ctrl_command_lcmt._get_packed_fingerprint())[0]

