"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class robot_power_io_lcmt(object):
    __slots__ = ["voltage1", "current1", "temperature1", "charge1", "health1", "cycle1", "voltage2", "current2", "temperature2", "charge2", "health2", "cycle2", "emy_stop"]

    __typenames__ = ["int32_t", "int32_t", "int8_t", "int8_t", "int8_t", "int16_t", "int32_t", "int32_t", "int8_t", "int8_t", "int8_t", "int16_t", "int8_t"]

    __dimensions__ = [None, None, None, None, None, None, None, None, None, None, None, None, None]

    def __init__(self):
        self.voltage1 = 0
        self.current1 = 0
        self.temperature1 = 0
        self.charge1 = 0
        self.health1 = 0
        self.cycle1 = 0
        self.voltage2 = 0
        self.current2 = 0
        self.temperature2 = 0
        self.charge2 = 0
        self.health2 = 0
        self.cycle2 = 0
        self.emy_stop = 0

    def encode(self):
        buf = BytesIO()
        buf.write(robot_power_io_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">iibbbhiibbbhb", self.voltage1, self.current1, self.temperature1, self.charge1, self.health1, self.cycle1, self.voltage2, self.current2, self.temperature2, self.charge2, self.health2, self.cycle2, self.emy_stop))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != robot_power_io_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return robot_power_io_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = robot_power_io_lcmt()
        self.voltage1, self.current1, self.temperature1, self.charge1, self.health1, self.cycle1, self.voltage2, self.current2, self.temperature2, self.charge2, self.health2, self.cycle2, self.emy_stop = struct.unpack(">iibbbhiibbbhb", buf.read(27))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if robot_power_io_lcmt in parents: return 0
        tmphash = (0x525b338e826d10) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if robot_power_io_lcmt._packed_fingerprint is None:
            robot_power_io_lcmt._packed_fingerprint = struct.pack(">Q", robot_power_io_lcmt._get_hash_recursive([]))
        return robot_power_io_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", robot_power_io_lcmt._get_packed_fingerprint())[0]

