"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class visual_servo_feedback_lcmt(object):
    __slots__ = ["fb_mode"]

    __typenames__ = ["int32_t"]

    __dimensions__ = [None]

    def __init__(self):
        self.fb_mode = 0

    def encode(self):
        buf = BytesIO()
        buf.write(visual_servo_feedback_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.fb_mode))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != visual_servo_feedback_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return visual_servo_feedback_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = visual_servo_feedback_lcmt()
        self.fb_mode = struct.unpack(">i", buf.read(4))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if visual_servo_feedback_lcmt in parents: return 0
        tmphash = (0x363333a97f3d1e2c) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if visual_servo_feedback_lcmt._packed_fingerprint is None:
            visual_servo_feedback_lcmt._packed_fingerprint = struct.pack(">Q", visual_servo_feedback_lcmt._get_hash_recursive([]))
        return visual_servo_feedback_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", visual_servo_feedback_lcmt._get_packed_fingerprint())[0]

