"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class walk_extra_command_lcmt(object):
    __slots__ = ["response_id", "foot_pos_final", "swing_type", "foot_pos_traj"]

    __typenames__ = ["int8_t", "double", "int8_t", "double"]

    __dimensions__ = [None, [12], None, [12, 10]]

    def __init__(self):
        self.response_id = 0
        self.foot_pos_final = [ 0.0 for dim0 in range(12) ]
        self.swing_type = 0
        self.foot_pos_traj = [ [ 0.0 for dim1 in range(10) ] for dim0 in range(12) ]

    def encode(self):
        buf = BytesIO()
        buf.write(walk_extra_command_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.response_id))
        buf.write(struct.pack('>12d', *self.foot_pos_final[:12]))
        buf.write(struct.pack(">b", self.swing_type))
        for i0 in range(12):
            buf.write(struct.pack('>10d', *self.foot_pos_traj[i0][:10]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != walk_extra_command_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return walk_extra_command_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = walk_extra_command_lcmt()
        self.response_id = struct.unpack(">b", buf.read(1))[0]
        self.foot_pos_final = struct.unpack('>12d', buf.read(96))
        self.swing_type = struct.unpack(">b", buf.read(1))[0]
        self.foot_pos_traj = []
        for i0 in range(12):
            self.foot_pos_traj.append(struct.unpack('>10d', buf.read(80)))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if walk_extra_command_lcmt in parents: return 0
        tmphash = (0x45094677375b3900) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if walk_extra_command_lcmt._packed_fingerprint is None:
            walk_extra_command_lcmt._packed_fingerprint = struct.pack(">Q", walk_extra_command_lcmt._get_hash_recursive([]))
        return walk_extra_command_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", walk_extra_command_lcmt._get_packed_fingerprint())[0]

