"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class walk_data_lcmt(object):
    __slots__ = ["refMPCLinPos_W", "refMPCLinVel_W", "refRobotLinPos_W", "desRobotLinPos_W", "desMPCLinVel_W", "swingLegCompensationByV_W", "pfx_rel", "pfy_rel", "lp_vx", "lp_vy", "isEarlyContact", "isDelayContact"]

    __typenames__ = ["float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float"]

    __dimensions__ = [[3], [3], [3], [3], [3], [6], [2], [2], [2], [2], [2], [2]]

    def __init__(self):
        self.refMPCLinPos_W = [ 0.0 for dim0 in range(3) ]
        self.refMPCLinVel_W = [ 0.0 for dim0 in range(3) ]
        self.refRobotLinPos_W = [ 0.0 for dim0 in range(3) ]
        self.desRobotLinPos_W = [ 0.0 for dim0 in range(3) ]
        self.desMPCLinVel_W = [ 0.0 for dim0 in range(3) ]
        self.swingLegCompensationByV_W = [ 0.0 for dim0 in range(6) ]
        self.pfx_rel = [ 0.0 for dim0 in range(2) ]
        self.pfy_rel = [ 0.0 for dim0 in range(2) ]
        self.lp_vx = [ 0.0 for dim0 in range(2) ]
        self.lp_vy = [ 0.0 for dim0 in range(2) ]
        self.isEarlyContact = [ 0.0 for dim0 in range(2) ]
        self.isDelayContact = [ 0.0 for dim0 in range(2) ]

    def encode(self):
        buf = BytesIO()
        buf.write(walk_data_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>3f', *self.refMPCLinPos_W[:3]))
        buf.write(struct.pack('>3f', *self.refMPCLinVel_W[:3]))
        buf.write(struct.pack('>3f', *self.refRobotLinPos_W[:3]))
        buf.write(struct.pack('>3f', *self.desRobotLinPos_W[:3]))
        buf.write(struct.pack('>3f', *self.desMPCLinVel_W[:3]))
        buf.write(struct.pack('>6f', *self.swingLegCompensationByV_W[:6]))
        buf.write(struct.pack('>2f', *self.pfx_rel[:2]))
        buf.write(struct.pack('>2f', *self.pfy_rel[:2]))
        buf.write(struct.pack('>2f', *self.lp_vx[:2]))
        buf.write(struct.pack('>2f', *self.lp_vy[:2]))
        buf.write(struct.pack('>2f', *self.isEarlyContact[:2]))
        buf.write(struct.pack('>2f', *self.isDelayContact[:2]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != walk_data_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return walk_data_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = walk_data_lcmt()
        self.refMPCLinPos_W = struct.unpack('>3f', buf.read(12))
        self.refMPCLinVel_W = struct.unpack('>3f', buf.read(12))
        self.refRobotLinPos_W = struct.unpack('>3f', buf.read(12))
        self.desRobotLinPos_W = struct.unpack('>3f', buf.read(12))
        self.desMPCLinVel_W = struct.unpack('>3f', buf.read(12))
        self.swingLegCompensationByV_W = struct.unpack('>6f', buf.read(24))
        self.pfx_rel = struct.unpack('>2f', buf.read(8))
        self.pfy_rel = struct.unpack('>2f', buf.read(8))
        self.lp_vx = struct.unpack('>2f', buf.read(8))
        self.lp_vy = struct.unpack('>2f', buf.read(8))
        self.isEarlyContact = struct.unpack('>2f', buf.read(8))
        self.isDelayContact = struct.unpack('>2f', buf.read(8))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if walk_data_lcmt in parents: return 0
        tmphash = (0x2838a2ef92dc66c8) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if walk_data_lcmt._packed_fingerprint is None:
            walk_data_lcmt._packed_fingerprint = struct.pack(">Q", walk_data_lcmt._get_hash_recursive([]))
        return walk_data_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", walk_data_lcmt._get_packed_fingerprint())[0]

