/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class ecat_debug_cmd_lcmt implements lcm.lcm.LCMEncodable
{
    public int dim;
    public short ctrlWord[];
    public float mc_kp[];
    public float mc_kd[];
    public float mc_tarPos[];
    public float mc_tarVel[];
    public float mc_tarTor[];
    public float original_tarPos[];
    public float original_tarVel[];
    public float original_tarTor[];
 
    public ecat_debug_cmd_lcmt()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x19ad9f353d6fd46cL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.ecat_debug_cmd_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.ecat_debug_cmd_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeInt(this.dim); 
 
        for (int a = 0; a < this.dim; a++) {
            outs.writeShort(this.ctrlWord[a]); 
        }
 
        for (int a = 0; a < this.dim; a++) {
            outs.writeFloat(this.mc_kp[a]); 
        }
 
        for (int a = 0; a < this.dim; a++) {
            outs.writeFloat(this.mc_kd[a]); 
        }
 
        for (int a = 0; a < this.dim; a++) {
            outs.writeFloat(this.mc_tarPos[a]); 
        }
 
        for (int a = 0; a < this.dim; a++) {
            outs.writeFloat(this.mc_tarVel[a]); 
        }
 
        for (int a = 0; a < this.dim; a++) {
            outs.writeFloat(this.mc_tarTor[a]); 
        }
 
        for (int a = 0; a < this.dim; a++) {
            outs.writeFloat(this.original_tarPos[a]); 
        }
 
        for (int a = 0; a < this.dim; a++) {
            outs.writeFloat(this.original_tarVel[a]); 
        }
 
        for (int a = 0; a < this.dim; a++) {
            outs.writeFloat(this.original_tarTor[a]); 
        }
 
    }
 
    public ecat_debug_cmd_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public ecat_debug_cmd_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.ecat_debug_cmd_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.ecat_debug_cmd_lcmt o = new lcmtypes.ecat_debug_cmd_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.dim = ins.readInt();
 
        this.ctrlWord = new short[(int) dim];
        for (int a = 0; a < this.dim; a++) {
            this.ctrlWord[a] = ins.readShort();
        }
 
        this.mc_kp = new float[(int) dim];
        for (int a = 0; a < this.dim; a++) {
            this.mc_kp[a] = ins.readFloat();
        }
 
        this.mc_kd = new float[(int) dim];
        for (int a = 0; a < this.dim; a++) {
            this.mc_kd[a] = ins.readFloat();
        }
 
        this.mc_tarPos = new float[(int) dim];
        for (int a = 0; a < this.dim; a++) {
            this.mc_tarPos[a] = ins.readFloat();
        }
 
        this.mc_tarVel = new float[(int) dim];
        for (int a = 0; a < this.dim; a++) {
            this.mc_tarVel[a] = ins.readFloat();
        }
 
        this.mc_tarTor = new float[(int) dim];
        for (int a = 0; a < this.dim; a++) {
            this.mc_tarTor[a] = ins.readFloat();
        }
 
        this.original_tarPos = new float[(int) dim];
        for (int a = 0; a < this.dim; a++) {
            this.original_tarPos[a] = ins.readFloat();
        }
 
        this.original_tarVel = new float[(int) dim];
        for (int a = 0; a < this.dim; a++) {
            this.original_tarVel[a] = ins.readFloat();
        }
 
        this.original_tarTor = new float[(int) dim];
        for (int a = 0; a < this.dim; a++) {
            this.original_tarTor[a] = ins.readFloat();
        }
 
    }
 
    public lcmtypes.ecat_debug_cmd_lcmt copy()
    {
        lcmtypes.ecat_debug_cmd_lcmt outobj = new lcmtypes.ecat_debug_cmd_lcmt();
        outobj.dim = this.dim;
 
        outobj.ctrlWord = new short[(int) dim];
        if (this.dim > 0)
            System.arraycopy(this.ctrlWord, 0, outobj.ctrlWord, 0, (int) this.dim); 
        outobj.mc_kp = new float[(int) dim];
        if (this.dim > 0)
            System.arraycopy(this.mc_kp, 0, outobj.mc_kp, 0, (int) this.dim); 
        outobj.mc_kd = new float[(int) dim];
        if (this.dim > 0)
            System.arraycopy(this.mc_kd, 0, outobj.mc_kd, 0, (int) this.dim); 
        outobj.mc_tarPos = new float[(int) dim];
        if (this.dim > 0)
            System.arraycopy(this.mc_tarPos, 0, outobj.mc_tarPos, 0, (int) this.dim); 
        outobj.mc_tarVel = new float[(int) dim];
        if (this.dim > 0)
            System.arraycopy(this.mc_tarVel, 0, outobj.mc_tarVel, 0, (int) this.dim); 
        outobj.mc_tarTor = new float[(int) dim];
        if (this.dim > 0)
            System.arraycopy(this.mc_tarTor, 0, outobj.mc_tarTor, 0, (int) this.dim); 
        outobj.original_tarPos = new float[(int) dim];
        if (this.dim > 0)
            System.arraycopy(this.original_tarPos, 0, outobj.original_tarPos, 0, (int) this.dim); 
        outobj.original_tarVel = new float[(int) dim];
        if (this.dim > 0)
            System.arraycopy(this.original_tarVel, 0, outobj.original_tarVel, 0, (int) this.dim); 
        outobj.original_tarTor = new float[(int) dim];
        if (this.dim > 0)
            System.arraycopy(this.original_tarTor, 0, outobj.original_tarTor, 0, (int) this.dim); 
        return outobj;
    }
 
}

