/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class ecat_debug_data_lcmt implements lcm.lcm.LCMEncodable
{
    public int dim;
    public short stat[];
    public short res1[];
    public short res2[];
    public float mc_curPos[];
    public float mc_curVel[];
    public float mc_curCur[];
    public float mc_curTor[];
    public float original_curPosH[];
    public float original_curPosL[];
    public float original_curVel[];
    public float original_curTor[];
 
    public ecat_debug_data_lcmt()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x4f6abd0226bb50f6L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.ecat_debug_data_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.ecat_debug_data_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeInt(this.dim); 
 
        for (int a = 0; a < this.dim; a++) {
            outs.writeShort(this.stat[a]); 
        }
 
        for (int a = 0; a < this.dim; a++) {
            outs.writeShort(this.res1[a]); 
        }
 
        for (int a = 0; a < this.dim; a++) {
            outs.writeShort(this.res2[a]); 
        }
 
        for (int a = 0; a < this.dim; a++) {
            outs.writeFloat(this.mc_curPos[a]); 
        }
 
        for (int a = 0; a < this.dim; a++) {
            outs.writeFloat(this.mc_curVel[a]); 
        }
 
        for (int a = 0; a < this.dim; a++) {
            outs.writeFloat(this.mc_curCur[a]); 
        }
 
        for (int a = 0; a < this.dim; a++) {
            outs.writeFloat(this.mc_curTor[a]); 
        }
 
        for (int a = 0; a < this.dim; a++) {
            outs.writeFloat(this.original_curPosH[a]); 
        }
 
        for (int a = 0; a < this.dim; a++) {
            outs.writeFloat(this.original_curPosL[a]); 
        }
 
        for (int a = 0; a < this.dim; a++) {
            outs.writeFloat(this.original_curVel[a]); 
        }
 
        for (int a = 0; a < this.dim; a++) {
            outs.writeFloat(this.original_curTor[a]); 
        }
 
    }
 
    public ecat_debug_data_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public ecat_debug_data_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.ecat_debug_data_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.ecat_debug_data_lcmt o = new lcmtypes.ecat_debug_data_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.dim = ins.readInt();
 
        this.stat = new short[(int) dim];
        for (int a = 0; a < this.dim; a++) {
            this.stat[a] = ins.readShort();
        }
 
        this.res1 = new short[(int) dim];
        for (int a = 0; a < this.dim; a++) {
            this.res1[a] = ins.readShort();
        }
 
        this.res2 = new short[(int) dim];
        for (int a = 0; a < this.dim; a++) {
            this.res2[a] = ins.readShort();
        }
 
        this.mc_curPos = new float[(int) dim];
        for (int a = 0; a < this.dim; a++) {
            this.mc_curPos[a] = ins.readFloat();
        }
 
        this.mc_curVel = new float[(int) dim];
        for (int a = 0; a < this.dim; a++) {
            this.mc_curVel[a] = ins.readFloat();
        }
 
        this.mc_curCur = new float[(int) dim];
        for (int a = 0; a < this.dim; a++) {
            this.mc_curCur[a] = ins.readFloat();
        }
 
        this.mc_curTor = new float[(int) dim];
        for (int a = 0; a < this.dim; a++) {
            this.mc_curTor[a] = ins.readFloat();
        }
 
        this.original_curPosH = new float[(int) dim];
        for (int a = 0; a < this.dim; a++) {
            this.original_curPosH[a] = ins.readFloat();
        }
 
        this.original_curPosL = new float[(int) dim];
        for (int a = 0; a < this.dim; a++) {
            this.original_curPosL[a] = ins.readFloat();
        }
 
        this.original_curVel = new float[(int) dim];
        for (int a = 0; a < this.dim; a++) {
            this.original_curVel[a] = ins.readFloat();
        }
 
        this.original_curTor = new float[(int) dim];
        for (int a = 0; a < this.dim; a++) {
            this.original_curTor[a] = ins.readFloat();
        }
 
    }
 
    public lcmtypes.ecat_debug_data_lcmt copy()
    {
        lcmtypes.ecat_debug_data_lcmt outobj = new lcmtypes.ecat_debug_data_lcmt();
        outobj.dim = this.dim;
 
        outobj.stat = new short[(int) dim];
        if (this.dim > 0)
            System.arraycopy(this.stat, 0, outobj.stat, 0, (int) this.dim); 
        outobj.res1 = new short[(int) dim];
        if (this.dim > 0)
            System.arraycopy(this.res1, 0, outobj.res1, 0, (int) this.dim); 
        outobj.res2 = new short[(int) dim];
        if (this.dim > 0)
            System.arraycopy(this.res2, 0, outobj.res2, 0, (int) this.dim); 
        outobj.mc_curPos = new float[(int) dim];
        if (this.dim > 0)
            System.arraycopy(this.mc_curPos, 0, outobj.mc_curPos, 0, (int) this.dim); 
        outobj.mc_curVel = new float[(int) dim];
        if (this.dim > 0)
            System.arraycopy(this.mc_curVel, 0, outobj.mc_curVel, 0, (int) this.dim); 
        outobj.mc_curCur = new float[(int) dim];
        if (this.dim > 0)
            System.arraycopy(this.mc_curCur, 0, outobj.mc_curCur, 0, (int) this.dim); 
        outobj.mc_curTor = new float[(int) dim];
        if (this.dim > 0)
            System.arraycopy(this.mc_curTor, 0, outobj.mc_curTor, 0, (int) this.dim); 
        outobj.original_curPosH = new float[(int) dim];
        if (this.dim > 0)
            System.arraycopy(this.original_curPosH, 0, outobj.original_curPosH, 0, (int) this.dim); 
        outobj.original_curPosL = new float[(int) dim];
        if (this.dim > 0)
            System.arraycopy(this.original_curPosL, 0, outobj.original_curPosL, 0, (int) this.dim); 
        outobj.original_curVel = new float[(int) dim];
        if (this.dim > 0)
            System.arraycopy(this.original_curVel, 0, outobj.original_curVel, 0, (int) this.dim); 
        outobj.original_curTor = new float[(int) dim];
        if (this.dim > 0)
            System.arraycopy(this.original_curTor, 0, outobj.original_curTor, 0, (int) this.dim); 
        return outobj;
    }
 
}

