/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class grid_map_lcmt implements lcm.lcm.LCMEncodable
{
    public float height_elevation[];
 
    public grid_map_lcmt()
    {
        height_elevation = new float[315];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xfd3de10beda5322eL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.grid_map_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.grid_map_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 315; a++) {
            outs.writeFloat(this.height_elevation[a]); 
        }
 
    }
 
    public grid_map_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public grid_map_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.grid_map_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.grid_map_lcmt o = new lcmtypes.grid_map_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.height_elevation = new float[(int) 315];
        for (int a = 0; a < 315; a++) {
            this.height_elevation[a] = ins.readFloat();
        }
 
    }
 
    public lcmtypes.grid_map_lcmt copy()
    {
        lcmtypes.grid_map_lcmt outobj = new lcmtypes.grid_map_lcmt();
        outobj.height_elevation = new float[(int) 315];
        System.arraycopy(this.height_elevation, 0, outobj.height_elevation, 0, 315); 
        return outobj;
    }
 
}

