/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class hitbot_data_lcmt implements lcm.lcm.LCMEncodable
{
    public byte status;
    public float position;
    public float current;
 
    public hitbot_data_lcmt()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xb89df6b682089526L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.hitbot_data_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.hitbot_data_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeByte(this.status); 
 
        outs.writeFloat(this.position); 
 
        outs.writeFloat(this.current); 
 
    }
 
    public hitbot_data_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public hitbot_data_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.hitbot_data_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.hitbot_data_lcmt o = new lcmtypes.hitbot_data_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.status = ins.readByte();
 
        this.position = ins.readFloat();
 
        this.current = ins.readFloat();
 
    }
 
    public lcmtypes.hitbot_data_lcmt copy()
    {
        lcmtypes.hitbot_data_lcmt outobj = new lcmtypes.hitbot_data_lcmt();
        outobj.status = this.status;
 
        outobj.position = this.position;
 
        outobj.current = this.current;
 
        return outobj;
    }
 
}

