/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class honsp_accuracy_lcmt implements lcm.lcm.LCMEncodable
{
    public float nsp_p[];
    public float nsp_v[];
    public float nsp_a[];
    public float nsp_p_all[];
    public float nsp_v_all[];
    public float nsp_a_all[];
    public float nsp_ddq[];
 
    public honsp_accuracy_lcmt()
    {
        nsp_p = new float[30];
        nsp_v = new float[30];
        nsp_a = new float[30];
        nsp_p_all = new float[30];
        nsp_v_all = new float[30];
        nsp_a_all = new float[30];
        nsp_ddq = new float[30];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x3e8f81401ce01256L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.honsp_accuracy_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.honsp_accuracy_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 30; a++) {
            outs.writeFloat(this.nsp_p[a]); 
        }
 
        for (int a = 0; a < 30; a++) {
            outs.writeFloat(this.nsp_v[a]); 
        }
 
        for (int a = 0; a < 30; a++) {
            outs.writeFloat(this.nsp_a[a]); 
        }
 
        for (int a = 0; a < 30; a++) {
            outs.writeFloat(this.nsp_p_all[a]); 
        }
 
        for (int a = 0; a < 30; a++) {
            outs.writeFloat(this.nsp_v_all[a]); 
        }
 
        for (int a = 0; a < 30; a++) {
            outs.writeFloat(this.nsp_a_all[a]); 
        }
 
        for (int a = 0; a < 30; a++) {
            outs.writeFloat(this.nsp_ddq[a]); 
        }
 
    }
 
    public honsp_accuracy_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public honsp_accuracy_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.honsp_accuracy_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.honsp_accuracy_lcmt o = new lcmtypes.honsp_accuracy_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.nsp_p = new float[(int) 30];
        for (int a = 0; a < 30; a++) {
            this.nsp_p[a] = ins.readFloat();
        }
 
        this.nsp_v = new float[(int) 30];
        for (int a = 0; a < 30; a++) {
            this.nsp_v[a] = ins.readFloat();
        }
 
        this.nsp_a = new float[(int) 30];
        for (int a = 0; a < 30; a++) {
            this.nsp_a[a] = ins.readFloat();
        }
 
        this.nsp_p_all = new float[(int) 30];
        for (int a = 0; a < 30; a++) {
            this.nsp_p_all[a] = ins.readFloat();
        }
 
        this.nsp_v_all = new float[(int) 30];
        for (int a = 0; a < 30; a++) {
            this.nsp_v_all[a] = ins.readFloat();
        }
 
        this.nsp_a_all = new float[(int) 30];
        for (int a = 0; a < 30; a++) {
            this.nsp_a_all[a] = ins.readFloat();
        }
 
        this.nsp_ddq = new float[(int) 30];
        for (int a = 0; a < 30; a++) {
            this.nsp_ddq[a] = ins.readFloat();
        }
 
    }
 
    public lcmtypes.honsp_accuracy_lcmt copy()
    {
        lcmtypes.honsp_accuracy_lcmt outobj = new lcmtypes.honsp_accuracy_lcmt();
        outobj.nsp_p = new float[(int) 30];
        System.arraycopy(this.nsp_p, 0, outobj.nsp_p, 0, 30); 
        outobj.nsp_v = new float[(int) 30];
        System.arraycopy(this.nsp_v, 0, outobj.nsp_v, 0, 30); 
        outobj.nsp_a = new float[(int) 30];
        System.arraycopy(this.nsp_a, 0, outobj.nsp_a, 0, 30); 
        outobj.nsp_p_all = new float[(int) 30];
        System.arraycopy(this.nsp_p_all, 0, outobj.nsp_p_all, 0, 30); 
        outobj.nsp_v_all = new float[(int) 30];
        System.arraycopy(this.nsp_v_all, 0, outobj.nsp_v_all, 0, 30); 
        outobj.nsp_a_all = new float[(int) 30];
        System.arraycopy(this.nsp_a_all, 0, outobj.nsp_a_all, 0, 30); 
        outobj.nsp_ddq = new float[(int) 30];
        System.arraycopy(this.nsp_ddq, 0, outobj.nsp_ddq, 0, 30); 
        return outobj;
    }
 
}

