/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class howbc_time_lcmt implements lcm.lcm.LCMEncodable
{
    public float t_total;
    public float t_obj;
    public float t_task_cons;
    public float t_final_verify;
    public float t_torque;
    public float t_pub;
    public float prior_num;
    public float prior_task[];
    public int contact_count;
 
    public howbc_time_lcmt()
    {
        prior_task = new float[10];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x66bece2a910ec18fL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.howbc_time_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.howbc_time_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeFloat(this.t_total); 
 
        outs.writeFloat(this.t_obj); 
 
        outs.writeFloat(this.t_task_cons); 
 
        outs.writeFloat(this.t_final_verify); 
 
        outs.writeFloat(this.t_torque); 
 
        outs.writeFloat(this.t_pub); 
 
        outs.writeFloat(this.prior_num); 
 
        for (int a = 0; a < 10; a++) {
            outs.writeFloat(this.prior_task[a]); 
        }
 
        outs.writeInt(this.contact_count); 
 
    }
 
    public howbc_time_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public howbc_time_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.howbc_time_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.howbc_time_lcmt o = new lcmtypes.howbc_time_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.t_total = ins.readFloat();
 
        this.t_obj = ins.readFloat();
 
        this.t_task_cons = ins.readFloat();
 
        this.t_final_verify = ins.readFloat();
 
        this.t_torque = ins.readFloat();
 
        this.t_pub = ins.readFloat();
 
        this.prior_num = ins.readFloat();
 
        this.prior_task = new float[(int) 10];
        for (int a = 0; a < 10; a++) {
            this.prior_task[a] = ins.readFloat();
        }
 
        this.contact_count = ins.readInt();
 
    }
 
    public lcmtypes.howbc_time_lcmt copy()
    {
        lcmtypes.howbc_time_lcmt outobj = new lcmtypes.howbc_time_lcmt();
        outobj.t_total = this.t_total;
 
        outobj.t_obj = this.t_obj;
 
        outobj.t_task_cons = this.t_task_cons;
 
        outobj.t_final_verify = this.t_final_verify;
 
        outobj.t_torque = this.t_torque;
 
        outobj.t_pub = this.t_pub;
 
        outobj.prior_num = this.prior_num;
 
        outobj.prior_task = new float[(int) 10];
        System.arraycopy(this.prior_task, 0, outobj.prior_task, 0, 10); 
        outobj.contact_count = this.contact_count;
 
        return outobj;
    }
 
}

