/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class leg_control_command_rl_lcmt implements lcm.lcm.LCMEncodable
{
    public float q_des[];
 
    public leg_control_command_rl_lcmt()
    {
        q_des = new float[12];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x52203debb7628520L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.leg_control_command_rl_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.leg_control_command_rl_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.q_des[a]); 
        }
 
    }
 
    public leg_control_command_rl_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public leg_control_command_rl_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.leg_control_command_rl_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.leg_control_command_rl_lcmt o = new lcmtypes.leg_control_command_rl_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.q_des = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.q_des[a] = ins.readFloat();
        }
 
    }
 
    public lcmtypes.leg_control_command_rl_lcmt copy()
    {
        lcmtypes.leg_control_command_rl_lcmt outobj = new lcmtypes.leg_control_command_rl_lcmt();
        outobj.q_des = new float[(int) 12];
        System.arraycopy(this.q_des, 0, outobj.q_des, 0, 12); 
        return outobj;
    }
 
}

