/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class lowlevel_command_struct implements lcm.lcm.LCMEncodable
{
    public float x_vel_des;
    public float y_vel_des;
    public float yaw_vel_des;
    public float z_des;
    public float stop;
    public byte is_stair;
 
    public lowlevel_command_struct()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x142cab22f0b85b50L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.lowlevel_command_struct.class))
            return 0L;
 
        classes.add(lcmtypes.lowlevel_command_struct.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeFloat(this.x_vel_des); 
 
        outs.writeFloat(this.y_vel_des); 
 
        outs.writeFloat(this.yaw_vel_des); 
 
        outs.writeFloat(this.z_des); 
 
        outs.writeFloat(this.stop); 
 
        outs.writeByte(this.is_stair); 
 
    }
 
    public lowlevel_command_struct(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public lowlevel_command_struct(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.lowlevel_command_struct _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.lowlevel_command_struct o = new lcmtypes.lowlevel_command_struct();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.x_vel_des = ins.readFloat();
 
        this.y_vel_des = ins.readFloat();
 
        this.yaw_vel_des = ins.readFloat();
 
        this.z_des = ins.readFloat();
 
        this.stop = ins.readFloat();
 
        this.is_stair = ins.readByte();
 
    }
 
    public lcmtypes.lowlevel_command_struct copy()
    {
        lcmtypes.lowlevel_command_struct outobj = new lcmtypes.lowlevel_command_struct();
        outobj.x_vel_des = this.x_vel_des;
 
        outobj.y_vel_des = this.y_vel_des;
 
        outobj.yaw_vel_des = this.yaw_vel_des;
 
        outobj.z_des = this.z_des;
 
        outobj.stop = this.stop;
 
        outobj.is_stair = this.is_stair;
 
        return outobj;
    }
 
}

