/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class manager_ctrl_data_lcmt implements lcm.lcm.LCMEncodable
{
    public byte ctrl_arr[];
 
    public manager_ctrl_data_lcmt()
    {
        ctrl_arr = new byte[16];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x594339f99a5dd80aL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.manager_ctrl_data_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.manager_ctrl_data_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.write(this.ctrl_arr, 0, 16);
 
    }
 
    public manager_ctrl_data_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public manager_ctrl_data_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.manager_ctrl_data_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.manager_ctrl_data_lcmt o = new lcmtypes.manager_ctrl_data_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.ctrl_arr = new byte[(int) 16];
        ins.readFully(this.ctrl_arr, 0, (int) 16); 
    }
 
    public lcmtypes.manager_ctrl_data_lcmt copy()
    {
        lcmtypes.manager_ctrl_data_lcmt outobj = new lcmtypes.manager_ctrl_data_lcmt();
        outobj.ctrl_arr = new byte[(int) 16];
        System.arraycopy(this.ctrl_arr, 0, outobj.ctrl_arr, 0, 16); 
        return outobj;
    }
 
}

