/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class t12_command_response implements lcm.lcm.LCMEncodable
{
    public byte robot_fsm_cmd;
    public byte a_flag;
    public byte b_flag;
    public byte c_flag;
    public byte d_flag;
    public float x_vel_des;
    public float y_vel_des;
    public float yaw_vel_des;
 
    public t12_command_response()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x0c62ed5e348c6bc6L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.t12_command_response.class))
            return 0L;
 
        classes.add(lcmtypes.t12_command_response.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeByte(this.robot_fsm_cmd); 
 
        outs.writeByte(this.a_flag); 
 
        outs.writeByte(this.b_flag); 
 
        outs.writeByte(this.c_flag); 
 
        outs.writeByte(this.d_flag); 
 
        outs.writeFloat(this.x_vel_des); 
 
        outs.writeFloat(this.y_vel_des); 
 
        outs.writeFloat(this.yaw_vel_des); 
 
    }
 
    public t12_command_response(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public t12_command_response(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.t12_command_response _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.t12_command_response o = new lcmtypes.t12_command_response();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.robot_fsm_cmd = ins.readByte();
 
        this.a_flag = ins.readByte();
 
        this.b_flag = ins.readByte();
 
        this.c_flag = ins.readByte();
 
        this.d_flag = ins.readByte();
 
        this.x_vel_des = ins.readFloat();
 
        this.y_vel_des = ins.readFloat();
 
        this.yaw_vel_des = ins.readFloat();
 
    }
 
    public lcmtypes.t12_command_response copy()
    {
        lcmtypes.t12_command_response outobj = new lcmtypes.t12_command_response();
        outobj.robot_fsm_cmd = this.robot_fsm_cmd;
 
        outobj.a_flag = this.a_flag;
 
        outobj.b_flag = this.b_flag;
 
        outobj.c_flag = this.c_flag;
 
        outobj.d_flag = this.d_flag;
 
        outobj.x_vel_des = this.x_vel_des;
 
        outobj.y_vel_des = this.y_vel_des;
 
        outobj.yaw_vel_des = this.yaw_vel_des;
 
        return outobj;
    }
 
}

