/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class visual_servo_feedback_lcmt implements lcm.lcm.LCMEncodable
{
    public int fb_mode;
 
    public visual_servo_feedback_lcmt()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x363333a97f3d1e2cL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.visual_servo_feedback_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.visual_servo_feedback_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeInt(this.fb_mode); 
 
    }
 
    public visual_servo_feedback_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public visual_servo_feedback_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.visual_servo_feedback_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.visual_servo_feedback_lcmt o = new lcmtypes.visual_servo_feedback_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.fb_mode = ins.readInt();
 
    }
 
    public lcmtypes.visual_servo_feedback_lcmt copy()
    {
        lcmtypes.visual_servo_feedback_lcmt outobj = new lcmtypes.visual_servo_feedback_lcmt();
        outobj.fb_mode = this.fb_mode;
 
        return outobj;
    }
 
}

