/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class walk_extra_command_lcmt implements lcm.lcm.LCMEncodable
{
    public byte response_id;
    public double foot_pos_final[];
    public byte swing_type;
    public double foot_pos_traj[][];
 
    public walk_extra_command_lcmt()
    {
        foot_pos_final = new double[12];
        foot_pos_traj = new double[12][10];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x45094677375b3900L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.walk_extra_command_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.walk_extra_command_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeByte(this.response_id); 
 
        for (int a = 0; a < 12; a++) {
            outs.writeDouble(this.foot_pos_final[a]); 
        }
 
        outs.writeByte(this.swing_type); 
 
        for (int a = 0; a < 12; a++) {
            for (int b = 0; b < 10; b++) {
                outs.writeDouble(this.foot_pos_traj[a][b]); 
            }
        }
 
    }
 
    public walk_extra_command_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public walk_extra_command_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.walk_extra_command_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.walk_extra_command_lcmt o = new lcmtypes.walk_extra_command_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.response_id = ins.readByte();
 
        this.foot_pos_final = new double[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.foot_pos_final[a] = ins.readDouble();
        }
 
        this.swing_type = ins.readByte();
 
        this.foot_pos_traj = new double[(int) 12][(int) 10];
        for (int a = 0; a < 12; a++) {
            for (int b = 0; b < 10; b++) {
                this.foot_pos_traj[a][b] = ins.readDouble();
            }
        }
 
    }
 
    public lcmtypes.walk_extra_command_lcmt copy()
    {
        lcmtypes.walk_extra_command_lcmt outobj = new lcmtypes.walk_extra_command_lcmt();
        outobj.response_id = this.response_id;
 
        outobj.foot_pos_final = new double[(int) 12];
        System.arraycopy(this.foot_pos_final, 0, outobj.foot_pos_final, 0, 12); 
        outobj.swing_type = this.swing_type;
 
        outobj.foot_pos_traj = new double[(int) 12][(int) 10];
        for (int a = 0; a < 12; a++) {
            System.arraycopy(this.foot_pos_traj[a], 0, outobj.foot_pos_traj[a], 0, 10);        }
 
        return outobj;
    }
 
}

